# Generated by Django 5.1 on 2024-08-19 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Modificado', models.DateTimeField(auto_now=True)),
                ('Status', models.BooleanField(default=True)),
                ('pk_publica', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Codigo', models.CharField(blank=True, max_length=60, null=True)),
                ('Id_Sku', models.CharField(default='', max_length=100)),
                ('Titulo', models.CharField(default='', max_length=100)),
                ('Descripción', models.CharField(blank=True, default='', max_length=500)),
                ('Disponibilidad', models.BooleanField(blank=True, default=False)),
                ('Precio', models.FloatField(blank=True, default=0.0)),
                ('Moneda', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=20)),
                ('Marca', models.CharField(blank=True, default='', max_length=100)),
                ('Unidad_medida', models.CharField(choices=[('pieza', 'pieza'), ('cajas', 'cajas'), ('kilos', 'kilos'), ('libras', 'libras')], default='pieza', max_length=20)),
                ('Cantidad', models.IntegerField(default=0)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creadorproducto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
