# Generated by Django 5.1 on 2024-08-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Imagen_QR',
            field=models.ImageField(blank=True, null=True, upload_to='imagenQR/'),
        ),
    ]
