# Generated by Django 5.1 on 2024-08-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_alter_producto_imagen_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Imagen_QR',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
