# Generated by Django 5.1 on 2024-08-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_alter_producto_imagen_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Imagen_QR',
            field=models.ImageField(blank=True, null=True, upload_to='imagenQR/'),
        ),
    ]
