# Generated by Django 5.1 on 2024-08-20 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0004_alter_producto_imagen_qr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Modificado', models.DateTimeField(auto_now=True)),
                ('Status', models.BooleanField(default=True)),
                ('pk_publica', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Codigo', models.CharField(blank=True, max_length=60, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('deposita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiendeposita', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depoproducto', to='producto.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Modificado', models.DateTimeField(auto_now=True)),
                ('Status', models.BooleanField(default=True)),
                ('pk_publica', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Codigo', models.CharField(blank=True, max_length=60, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retiroproducto', to='producto.producto')),
                ('retira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quienretiro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
