# Generated by Django 5.1 on 2024-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Tipo',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Coordinador', 'Coordinador'), ('Servicio', 'Servicio'), ('Cliente', 'Cliente')], default='Coordinador', max_length=20),
        ),
    ]
