# Generated by Django 5.1 on 2024-08-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Tipo',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Coordinador', 'Coordinador'), ('Servicio', 'Servicio'), ('Almacen', 'Almacen')], default='Coordinador', max_length=20),
        ),
    ]
